### PR TITLE
remove redundant import and function

### PR DESCRIPTION
**Pull request by dcrowTMH**
Just trying to remove the redundant code and those import that's no longer using.
Finally understood how to interact with others in Git. Usually I was using bitbucket.
See if you think the changes is good and we can continue work together if you have any other ideas.

### CODE REVIEW

**Comment by errchh** [comment]
Brilliant. Merged your code~ 

For deployment, instead of Docker, shall we try deploying it on a server eg PythonAnywhere? 
-- create a flask local API server, to interact with Ollama. 
-- host ui.py on PythonAnywhere. add a http request to interact with the local API 

So, what do you reckon? 

I have found some sample code here: 
https://gigops.notion.site/PythonAnywhere-HTTP-request-Flask-API-14ae3f3b6ef08082b2dbf8b555bd3256

**Comment by dcrowTMH** [comment]
> Brilliant. Merged your code~
> 
> For deployment, instead of Docker, shall we try deploying it on a server eg PythonAnywhere? -- create a flask local API server, to interact with Ollama. -- host ui.py on PythonAnywhere. add a http request to interact with the local API
> 
> So, what do you reckon?
> 
> I have found some sample code here: https://gigops.notion.site/PythonAnywhere-HTTP-request-Flask-API-14ae3f3b6ef08082b2dbf8b555bd3256

Yes, if you are using PythonAnywhere. I think it's better to change it from streamilt to Flask for deployment.
I checked online that the infrastructure will be matching for PythonAnywhere.

I would say we can work in both directions? Coz Docker image is also quite useful for other deployments.
Let's take your direction first and we can come back to Docker later if you would like to learn about it together.

**Comment by errchh** [comment]
Yes sure. We can work on Docker now as to continue what we left off in PyCon. 

Reference: I played around Open Web UI for Ollama. There are two install options — 

1. A docker container for Client have already installed ollama app by himself. 
2. ollama lives inside the docker container. 

— for option 1. 
https://www.docker.com/blog/how-to-dockerize-your-python-applications/

— for option 2. Ensure smooth onboarding as a user’s point of view? 
— if there are 2 ollama, how to pull LLM to the one in the docker but not the other? 

And is there any other issue to consider / think of?

**Comment by errchh** [comment]
Maybe I can work on option 1 -- something direct to start with. 

Would you like to look into and carry on with option 2?

**Comment by dcrowTMH** [comment]
> Maybe I can work on option 1 -- something direct to start with.
> 
> Would you like to look into and carry on with option 2?

Sure. Let me look into option 2 and see what we can work on!

**Comment by dcrowTMH** [comment]
@errchh https://ollama.com/blog/ollama-is-now-available-as-an-official-docker-image
I think ollama is available in the docker image now. Not sure if it's something you are thinking of.
In the script, it can just target the ollama with correct name?

**Comment by errchh** [comment]
-- If my terms / vocabularies are not correct please correct and bare with me. 

https://ollama.com/blog/ollama-is-now-available-as-an-official-docker-image
I guess this refers to running Ollama itself? Run as an app, or run inside docker? 

Backgroud -- the other app OpenWebUI, a frontend for Ollama, also deploy using Docker. If I have read it correctly there are 2 options: 

1. user has installed ollama already, by themselves. Then there is a Docker version for this. https://github.com/open-webui/open-webui?tab=readme-ov-file#installation-with-default-configuration. 
2. user does not have ollama installed. The there is another Docker with ollama included / help installing along with OpenWebUI. https://github.com/open-webui/open-webui?tab=readme-ov-file#installation-with-default-configuration

So, similar situation? 
-- instruct user to have Ollama installed beforehand, then use the Docker image. 
-- or, if user does not have Ollama, the corresponding in Dockerfile?

**Comment by dcrowTMH** [comment]
No worries and I see what you meant now.
Yes. I think we can consider both situation then.

I expect then we can create two image then.
One is the user have Ollama installed beforehand, then it can use the image to initiate our UI and a ollama model which they have installed already. Then both can be interacted.

Another one is the user does not have Ollama then the image can initiate both UI and ollama model by using the image and both can be interacted.

Let me know if I am correct or not.
Please let me know which one you gonna look into and I work on another one.

I also checked is it possible to launch ollama on pythonanywhere but seems it's not possible as the quota will be used up quickly.
Here's a post for your reference.
https://www.pythonanywhere.com/forums/topic/35302/

**Comment by errchh** [comment]
The 2 docker images -- yes, totally. That's correct. 

Would you like to take the one initiate both UI and Ollama by the image? Sounds more challenging. -- when finished, could you briefly update me about how this is implemented? 

If so, I would take the one initiate UI only. -- I have started a bit but have error on the line about requirements.txt. I'll come back to this later. 

===== other thoughts =====

If deploy as web app -- think as if deploying a gen AI web app. then it either utilises web GPU, or edge(?) device GPU. 

Web GPU -- If can access web GPU, the app can use API directly e.g. OpenAI API key. 

Device GPU -- google has a thing called WebAI. on javascript. for gen AI web app and use GPU e.g. on the phone. 

I guess this would be popular. cloud GPU on chatbot adds up and will cost companies. e.g ecommerce. WebAI offload the work to device GPU then no cost on companies. 

https://io.google/2024/explore/d26017f3-9580-43bb-a6b9-c40066eb61b6/

**Pull request merged**
